name: Run Cypress Tests

on:
  push:
    branches:
      - main      # Trigger on push to the main branch
  pull_request:
    branches:
      - main      # Trigger on pull request to the main branch

jobs:
  cypress:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the CI environment

    steps:
      # Step 1: Check out the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'    # Use Node.js v16 (you can use other versions as required)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Run Cypress tests
      - name: Run Cypress tests
        run: |
          npx cypress run  # Run tests in headless mode
