name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies for the Node.js app
      - name: Install app dependencies
        run: |
          cd node-app && npm install  # Navigate to node-app and install app dependencies

      # Step 4: Install Cypress dependencies
      - name: Install Cypress
        run: |
          cd node-app && npm install cypress --save-dev  # Install Cypress in the node-app directory

      # Step 5: Start Node.js app in the background
      - name: Start Node.js app
        run: |
          cd node-app && nohup node app.js &  # Start the app in the background
        env:
          NODE_ENV: development

      # Step 6: Wait for the server to be ready
      - name: Wait for the server to be ready
        run: |
          sleep 10  # Wait for 10 seconds to ensure the Node.js app has started

      # Step 7: Run Cypress tests
      - name: Run Cypress tests
        run: |
          cd node-app && npx cypress run  # Run Cypress tests
