name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies in the correct directory
      - name: Install dependencies
        run: |
          cd node-app && npm install  # Navigate to node-app and install dependencies

      # Step 4: Start Node.js app in the background
      - name: Start Node.js app
        run: |
          cd node-app && nohup node app.js &  # Start the app in the background from the node-app directory
        env:
          NODE_ENV: development

      # Step 5: Wait for the server to be ready (Optional: Increase time if necessary)
      - name: Wait for the server to be ready
        run: |
          sleep 10  # Wait for 10 seconds to ensure the Node.js app has started

      # Step 6: Run Cypress tests
      - name: Run Cypress tests
        run: |
          npx cypress run
